<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <?php if(!$has_session = session_status() == PHP_SESSION_ACTIVE)
    {
    session_start();
    }
    if(!isset($_SESSION["ajaxToken"])){
        $_SESSION["ajaxToken"] = substr(str_shuffle(MD5(microtime())),0,20);
        $_SESSION['ajaxTokenTime'] = time();
    }
    if(time() - $_SESSION['ajaxTokenTime'] >= 600);{
        $_SESSION['ajaxTokenTime'] = time();
    }
    ?>
    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="/css/bootstrap-theme.css" rel="stylesheet">
    <!--custom CSS theme -->
    <link href="/css/my-style.css" rel="stylesheet">
    <title>Forum - <?php echo $view->pageTitle; ?></title>
</head>
<body>
<h1>Assassin's creed forum</h1>
<nav class="navbar navbar-inverse">
    <div class="container-fluid">

        <ul class="nav navbar-nav">
            <li><a href="../../index.php">Home</a></li>
                    <li><a href="../../index.php">View categories</a></li></ul>
            </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
            <?php
        if(isset($_SESSION['user_name']))
            {?>
                <li><a href="../../chats.php"><span class="glyphicon glyphicon-envelope yellow"></span> Messages</a></li>
                <li><a href="../../log_out.php"><span class="glyphicon glyphicon-log-out red"></span> Sign out</a></li>
            <?php }
        else
         {?>
            <li><a href="../../sign_up.php"><span class="glyphicon glyphicon-user green"></span> Sign Up</a></li>
            <li><a href="../../sign_in.php"><span class="glyphicon glyphicon-log-in green"></span> Login</a></li>
            <?php } ?>
        </ul>
    </div>
</nav>
        <div id="content">
        